Metrics/LineLength:
  # Exclude the message generation tests and message model. They 
  # deliberately create long messages.
  Exclude:
    - 'app/models/message.rb'
    - 'spec/features/messages/post_message_spec.rb'
    - 'spec/factories/messages.rb'
    - 'spec/controllers/messages_controller_spec.rb'
  Max: 125

# rake db:migrate updates this file to have an empty line, so write it out of rubocop
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

# db migrate files include long numbers and rarely need to be read by humans
Style/NumericLiterals:
  MinDigits: 15
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

# rake db:migrate updates this file to use double quotes, so write it out of rubocop
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'




