# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70bf696a3b0531a255d412617bfa28b4a7287d5cf1c12ffcc822bdcc229ab340150181b044b9af226413e5d0d68258284565a0b76ddb4d628a891420f9297bc6

test:
  secret_key_base: 7899ff9ad943c9383495b22da43432512fa1dd1b6d1310afaec4d045211eb9b077e717d86fe9b2aaf62c2c3625ae9dc386acbeeb908a1c76b7c2bf3d55d8cc6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
